on:
  schedule:
    - cron:  '0 0 * * 1,2,3,4,5'

jobs:
  build_docker_image:
    name: "Call build and push action"
    uses: ./.github/workflows/build-and-push-Docker-image.yml
    secrets: inherit
    with:
      image-name: ${{ github.repository }}
      image-tag: nightly
