---
name: Build and push docker image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    outputs:
      full-image-name:
        description: "Full pushed image name including host/registry, name, and tag"
        value: ${{ jobs.docker.outputs.full-image-name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    timeout-minutes: 25
    outputs:
      full-image-name: ${{ steps.image-name.outputs.full-image-name }}

    steps:

      - name: Define image name
        id: image-name
        run: |
          full_image_name="ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ inputs.image-tag }}"
          full_image_name=$(echo $full_image_name | tr '[A-Z]' '[a-z]')
          echo "full-image-name=$full_image_name" >> "$GITHUB_OUTPUT"
          echo "$full_image_name" > full-image-name

      - uses: actions/upload-artifact@v3
        with:
          name: full-image-name
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.image-name.outputs.full-image-name }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
          no-cache-filters: install-pacta

  check-system-dependencies:
    name: "Check System Dependencies"
    needs: docker
    uses: ./.github/workflows/check-R-sysdeps.yml
    with:
      image: ${{ needs.docker.outputs.full-image-name }}